/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "primary": "#865043",
        "primary-container": "#f4af9e",
        "primary-fixed": "#ffdad2",
        "primary-fixed-dim": "#fcb6a5",
        "on-primary": "#ffffff",
        "on-primary-container": "#734034",
        "on-primary-fixed": "#351007",
        "on-primary-fixed-variant": "#6a392d",
        "secondary": "#695b57",
        "secondary-container": "#f2ded9",
        "secondary-fixed": "#f2ded9",
        "secondary-fixed-dim": "#d5c3be",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#70615d",
        "on-secondary-fixed": "#231916",
        "on-secondary-fixed-variant": "#514440",
        "tertiary": "#675c58",
        "tertiary-container": "#cbbdb7",
        "tertiary-fixed": "#eedfda",
        "tertiary-fixed-dim": "#d2c4be",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#564c48",
        "on-tertiary-fixed": "#211a17",
        "on-tertiary-fixed-variant": "#4e4541",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#fff8f6",
        "on-background": "#201a19",
        "surface": "#fff8f6",
        "surface-bright": "#fff8f6",
        "surface-dim": "#e3d8d5",
        "surface-tint": "#865043",
        "surface-variant": "#ebe0dd",
        "surface-container": "#f7ebe8",
        "surface-container-low": "#fdf1ee",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#f1e6e3",
        "surface-container-highest": "#ebe0dd",
        "on-surface": "#201a19",
        "on-surface-variant": "#514440",
        "outline": "#83746f",
        "outline-variant": "#d5c3bd",
        "inverse-surface": "#352f2d",
        "inverse-on-surface": "#faeeeb",
        "inverse-primary": "#fcb6a5",
      },
      fontFamily: {
        "headline": ["PlusJakartaSans_700Bold", "PlusJakartaSans_800ExtraBold"],
        "headline-bold": ["PlusJakartaSans_800ExtraBold"],
        "body": ["Manrope_400Regular", "Manrope_500Medium"],
        "body-medium": ["Manrope_500Medium"],
        "body-semibold": ["Manrope_600SemiBold"],
        "body-bold": ["Manrope_700Bold"],
        "label": ["Manrope_700Bold"],
      },
      borderRadius: {
        "DEFAULT": 16,
        "lg": 32,
        "xl": 48,
        "full": 9999,
      },
    },
  },
  plugins: [],
};
